# example workflow for Coverity on Polaris
# sample 1
name: coverity-on-polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    # - name: Setup Java JDK
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: 17
    #     distribution: microsoft
    #     cache: maven
    - name: Polaris Scan
      env:
        POLARIS_SERVER_URL: ${{ secrets.POLARIS_SERVER_URL }}
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      run: |
        curl -fLsS -o polaris.zip $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d ${{ runner.temp }} -jo polaris.zip && rm -f polaris.zip
        ${{ runner.temp }}/polaris --co project.name=test-${{ github.event.repository.name }} analyze -w
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: polaris-cli-logs
#        path: ${{ github.workspace }}/.synopsys
